branch-defaults:
  master:
    environment: downstreamScm-env
environment-defaults:
  downstreamScm-env:
    branch: null
    repository: null
  node-express-env2:
    branch: null
    repository: null
global:
  application_name: Downstream SCM
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
